# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
  - package-ecosystem: "pub"
    directory: "/kits/flutter_ume_kit_channel_monitor"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
  - package-ecosystem: "pub"
    directory: "/kits/flutter_ume_kit_console"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
  - package-ecosystem: "pub"
    directory: "/kits/flutter_ume_kit_device"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
  - package-ecosystem: "pub"
    directory: "/kits/flutter_ume_kit_dio"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
  - package-ecosystem: "pub"
    directory: "/kits/flutter_ume_kit_perf"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
  - package-ecosystem: "pub"
    directory: "/kits/flutter_ume_kit_show_code"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
  - package-ecosystem: "pub"
    directory: "/kits/flutter_ume_kit_ui"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5