name: flutter_ume_kit_network
description: Network traffic kit for flutter_ume.
version: 0.2.0-dev.0
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  flutter_ume: '>=0.2.0-dev.0 <0.3.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
