name: coverage

on:
  push:
    branches:
      - master
    paths:
      - "lib/**"
      - "kits/flutter_ume_kit_console/lib/**"
      - "kits/flutter_ume_kit_device/lib/**"
      - "kits/flutter_ume_kit_perf/lib/**"
      - "kits/flutter_ume_kit_show_code/lib/**"
      - "kits/flutter_ume_kit_ui/lib/**"
      - "kits/flutter_ume_kit_dio/lib/**"
    tags:
      - "coverage-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF }}
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: |
          flutter pub get
          flutter pub run flutter_coverage_badge --exclude lib/util/flutter_logo.dart
      - run: |
          flutter pub get
          flutter pub run flutter_coverage_badge
        working-directory: kits/flutter_ume_kit_device
      - run: |
          flutter pub get
          flutter pub run flutter_coverage_badge
        working-directory: kits/flutter_ume_kit_perf
      - run: |
          flutter pub get
          flutter pub run flutter_coverage_badge --exclude lib/show_code/syntax_highlighter.dart
        working-directory: kits/flutter_ume_kit_show_code
      - run: |
          flutter pub get
          flutter pub run flutter_coverage_badge --exclude lib/third_party/cyclop
        working-directory: kits/flutter_ume_kit_ui
      - run: |
          flutter pub get
          flutter pub run flutter_coverage_badge
        working-directory: kits/flutter_ume_kit_console
      - run: |
          flutter pub get
          flutter pub run flutter_coverage_badge
        working-directory: kits/flutter_ume_kit_dio
      - name: Commit badges
        run: |
          git config --global user.name smileShirely
          git config --global user.email smileShirely@users.noreply.github.com
          git add coverage_badge.svg kits/flutter_ume_kit_device/coverage_badge.svg kits/flutter_ume_kit_perf/coverage_badge.svg kits/flutter_ume_kit_show_code/coverage_badge.svg kits/flutter_ume_kit_ui/coverage_badge.svg kits/flutter_ume_kit_console/coverage_badge.svg kits/flutter_ume_kit_dio/coverage_badge.svg
          git commit -m "Automated report coverage"
          git push
