name: Release & build example

on:
  push:
    tags:
      - "v*"

jobs:
  release-to-gitHub:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: "stable"
      - run: flutter pub get
        working-directory: example
      - run: flutter build apk --debug
        working-directory: example
      - uses: softprops/action-gh-release@v1
        with:
          files: example/build/app/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
