name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '11.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter test --enable-vmservice
      - run: flutter test --enable-vmservice
        working-directory: kits/flutter_ume_kit_device
      - run: flutter test --enable-vmservice
        working-directory: kits/flutter_ume_kit_perf
      - run: flutter test --enable-vmservice
        working-directory: kits/flutter_ume_kit_show_code
      - run: flutter test --enable-vmservice
        working-directory: kits/flutter_ume_kit_ui
      - run: flutter test --enable-vmservice
        working-directory: kits/flutter_ume_kit_console
      - run: flutter test --enable-vmservice
        working-directory: kits/flutter_ume_kit_dio
